###
GET http://localhost:3000/users



###
GET http://localhost:3000/users/60bc17f45804353b283bf55a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGJjMTdmNDU4MDQzNTNiMjgzYmY1NWEiLCJpYXQiOjE2MjI5Mzk2MzZ9.vxqRp_sr6d_75yE4rglH5vO_4bAoae2iYnh_qulq2xI

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Sand6",
    "email": "lata@gmail.com",
    "subscribedToChannel": "OyinChi",
    "password": "phpandjs"
}

###
PATCH http://localhost:3000/users/60b771082216c24274eea650
Content-Type: application/json

{  
    "subscribedToChannel": "Nodes"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{  
    "email": "h@gmail.com",
    "password": "phpandjs"
}

###
POST http://localhost:3000/users/logoutAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGJjMTdmNDU4MDQzNTNiMjgzYmY1NWEiLCJpYXQiOjE2MjI5Mzk2MzZ9.vxqRp_sr6d_75yE4rglH5vO_4bAoae2iYnh_qulq2xI