###
GET http://localhost:3000/users


###
GET http://localhost:3000/users/60acc6e769c737a23c03eeb0

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Sand6",
    "email": "h@gmail.com",
    "subscribedToChannel": "OyinChi",
    "password": "phpandjs"
}

###
PATCH http://localhost:3000/users/60b771082216c24274eea650
Content-Type: application/json

{  
    "subscribedToChannel": "Nodes"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{  
    "email": "tata@gmail.com",
    "password": "phpandjs"
}
